FROM python

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_DEBUG=False

COPY . .
COPY docker-entrypoint.sh /app/docker-entrypoint.sh

RUN apt-get update && apt-get install -y postgresql-client
RUN pip install -r requirements.txt
RUN pip install gunicorn
RUN mkdir -p /var/run/gunicorn
RUN chmod +x /app/docker-entrypoint.sh

ENTRYPOINT ["/app/docker-entrypoint.sh"]

CMD [ "gunicorn", "-w", "3", "--bind", "unix:/var/run/gunicorn/gunicorn.sock", "config.wsgi" ]
