PERMISSION_ADMIN = 'admin'
PERMISSION_SHOP = 'shop'
PERMISSION_NEWS = 'news'
PERMISSION_MENU = 'menu'
PERMISSION_EVENT = 'event'
PERMISSION_BAND = 'band'
PERMISSION_KARAOKE = 'karaoke'
PERMISSION_INVITE_USER = 'invite_user'
PERMISSION_INSPECTION = 'inspection'

HTTP_RESPONSE_CODE_SUCCESS = 200
HTTP_RESPONSE_CODE_CREATED = 201
HTTP_RESPONSE_CODE_BAD_REQUEST = 400
HTTP_RESPONSE_CODE_UNAUTHORIZED = 401
HTTP_RESPONSE_CODE_FORBIDDEN = 403
HTTP_RESPONSE_CODE_NOT_FOUND = 404
HTTP_RESPONSE_CODE_METHOD_NOT_ALLOWED = 405

